### ISSUE TITLE
IC2 Consumers need to be replaced on unload

### ISSUE THREAD

**Issue by Robotia** [covers1624/PowerConverters#28]
@covers1624 
This problem is using the latest PR of PowerConverters on curse. If you need pictures I can try to get some.

When a chunk is unloaded, the IC2 consumer connected to an energy bridge stops working. Even if wires are replaced, it simply does not start working. The energy bridge recognizes that the IC2 consumer is there and has 100% internal charge, but it just doesn't convert. Upon replacing the consumer with **no other changes**, the setup starts working again.
Players using the HV consumer have reported this to me. 

I know some basic Forge Java but I haven't looked into the code of PowerConverters much, any idea what this might be caused by?

**Comment by covers1624** [comment]
Ill speak to the owner of IC2 Classic and see what he says.

**Comment by Robotia** [comment]
@covers1624 awesome.

**Comment by Robotia** [comment]
Any update?

**Comment by covers1624** [comment]
Not yet unfortunately,  @Speiger needs to get on TS xD

**Comment by Robotia** [comment]
Which TS? :stuck_out_tongue:  I would like to join.

**Comment by Speiger** [comment]
@Robotia which Ic2 Classic version do you use?
If you are using below the latest (1.1.3.7) then it is because you did not use the version where it is fixed...
(Its a chunkUnload/blockUpdate thingy)

**Comment by Robotia** [comment]
I cannibalized the files from the latest so I could merge it with 1.1.3.5. I replaced everything except the IC2 main class and never added PE integration.

**Comment by Speiger** [comment]
@Robotia just delete the PEIntegration folder and everything is fine.
Every folder that is a Intigration/Integration can be deleted without causing a crash...
But 1.1.3.7 is a important fix....

**Comment by Robotia** [comment]
@Speiger I didn't want the client-side version to have to change so I applied the diffs only server-side.

I moved the following files from the v1.1.3.7 jar to the v.1.1.3.5 jar:
TileEntityGeoGenerator
TileEntitySolarGenerator
BlockElectric
StackUtil

I didn't change the actual IC2 class, could that be causing problems?

**Comment by Speiger** [comment]
@Robotia you know when you play on a server that the client gets the server sided EMC Values right?
So no Plugin no EMC Values... And no there are a lot more changes then these classes...
So just throw the IC2 1.1.3.7 on your server where the EMC Plugin is missed and you will have no problems...

**Comment by Robotia** [comment]
@Speiger already merged everything except PE integration with no problems. These producers were my only worry. @covers1624  do you use QmunityLib?

**Comment by covers1624** [comment]
@Robotia I do not use Qmunity Lib, and try this build: http://adel.podgeweb.com:8080/job/Power%20Converters/116/

**Comment by Robotia** [comment]
@covers1624 Thanks I will try it out.

**Comment by Robotia** [comment]
@covers1624 Doesn't work. New problems have come up.
`
java.lang.ArrayIndexOutOfBoundsException: -1
        at covers1624.powerconverters.tile.ic2.TileEntityIndustrialCraftProducer.getMaxEnergyOutput(TileEntityIndustrialCraftProducer.java:78)
        at covers1624.powerconverters.tile.ic2.TileEntityIndustrialCraftProducer.getOfferedEnergy(TileEntityIndustrialCraftProducer.java:88)
        at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:802)
        at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:163)
        at ic2.core.IC2.onTickEnd(IC2.java:2097)
        at ic2.core.IC2.onWorldTick(IC2.java:1993)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_IC2_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by Robotia** [comment]
@covers1624 I think something's up with the NBT, I reverted and the crash is still occurring. Going to edit the code and catch the exception to return 0.

**Comment by Robotia** [comment]
@covers1624 The update messed up getPowerSystem().getVoltageValues(). I have custom put in those values now.

**Comment by covers1624** [comment]
i have added checks in the code for this issue, yeah the nbt was broken, try this one http://adel.podgeweb.com:8080/job/Power%20Converters/117/

**Comment by Robotia** [comment]
@covers1624 Spam of `[21:40:39 ERROR]: Tile IC2Producer at  { X,Y,Z;UNKNOWN} needs to be replaced!`. IC2 Producers work but don't show up as linked the converter gui. I'm just going to hold onto what I had earlier and not worry about this I guess, instead just make something that auto-replaces them on chunk load.

**Comment by covers1624** [comment]
Did you replace the block? that would have fixed it.

**Comment by Robotia** [comment]
@covers1624 I was at a different location, that was not my setup. Someone else's setup was having problems. :/

**Comment by Robotia** [comment]
@covers1624 Are you on IRC?

**Comment by covers1624** [comment]
sure am #PowerConverters or #LegacyFarms

**Comment by Magicfar4** [comment]
I am using the latest version of the modifications that are in the picture.
And notice that the Problem, kakraz still in IC2 Producer
I do not know who the IC2. or PowerConverters, but one of them remembers its position in the world.
And install it on the same location, nothing happens.
And if you change the position, then the result will be successful.


![image](https://cloud.githubusercontent.com/assets/15196841/16545422/3e7a4da2-4133-11e6-9474-7b0619ba5430.png)

The unit recorded a producer who was in the wrong place.
After reload, the chunk was rearranged to another place.

**Comment by Speiger** [comment]
@Magicfar4 is that IC2 Exp 1.9-1.10? If yes then this is a normal bug because the current dev of the energynet has not understood the mistakes he did on it...

**Comment by Magicfar4** [comment]
No. My version is: "version": "2.2.817-experimental".

**Comment by Speiger** [comment]
@Magicfar4 was at the place where the 1 is a IC2 Producer or Consumer?
If yes then covers does the unloading wrong because the energynet still thinks: there is a Target/Source and the cables show what the energynet thinks...

**Comment by Magicfar4** [comment]
Yes , the place was a producer .

I will hope that the problem will be correcting ...

**Comment by Speiger** [comment]
well while reading his source i found a couple small bugs in the code (mostly lazyness bugs) but nothing that could cause that... Does that happening all the time or randomly @Magicfar4 
Also just a question: Do you play on a server or client only? There are random cases where that actually can happen...

**Comment by Speiger** [comment]
Also do not think in 1.7.10 that will be fixed on either side. IC2 Exp dropped 1.7.10 same goes this mod and its owner... And to let a quality version behind is not a priority just to be up to date...

**Comment by Magicfar4** [comment]
@Speiger , with this modification check is performed on the server and in a single game.
And I think that if you put it on the server , where I play , then work it never will :(

**Comment by Speiger** [comment]
(thats why i made my own internal converters) to not rely on something like that and still have compat xD

**Comment by Magicfar4** [comment]
@Speiger , its internal converters ; )
Tempting ... I would like a little more knowledge of modding and he would have done ...

**Comment by Obliterous** [comment]
So, this is not going to be fixed?

**Comment by Speiger** [comment]
I Highly Doubt it @Obliterous. @covers1624 is a person who easly say: I Fix it in 1.10... So do not think that he is going to fix it...

**Comment by covers1624** [comment]
If i ever do another 1.7 round yes. Otherwise it will be fixed in 1.10. At this point 1.7 is basically dead so i see no reason to support it, i have moved on to 1.10 and apart from critical fixes (i.e break your server issues) i wont support 1.7.

**Comment by Speiger** [comment]
1.7.10 has more then enough people on that version (and proberly will have it longer then 1.1x) to support it... I suggest to fix it.

**Comment by Obliterous** [comment]
considering that most of the mods that my server uses do not support 
1.1x, myself and all of my players will stick to 1.7.10.
